name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Ruby ${{ matrix.ruby }} + Faraday ${{ matrix.faraday }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "head"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "jruby-head"
        faraday:
          - "~> 1.0"
          - "~> 2.0"
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake
